// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8_H5pY6SfTzpRAi_KesieBpsd5iV5OGE',
    appId: '1:608053803585:android:b63a6bab462836af6f64c0',
    messagingSenderId: '608053803585',
    projectId: 'schedulegenerator-8c388',
    storageBucket: 'schedulegenerator-8c388.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRg2QcorzgPYiOdHEUSd5VtnrhTm5TojY',
    appId: '1:608053803585:ios:a71e1caddc0b0bc06f64c0',
    messagingSenderId: '608053803585',
    projectId: 'schedulegenerator-8c388',
    storageBucket: 'schedulegenerator-8c388.firebasestorage.app',
    iosBundleId: 'com.example.schedulegenerator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRg2QcorzgPYiOdHEUSd5VtnrhTm5TojY',
    appId: '1:608053803585:ios:a71e1caddc0b0bc06f64c0',
    messagingSenderId: '608053803585',
    projectId: 'schedulegenerator-8c388',
    storageBucket: 'schedulegenerator-8c388.firebasestorage.app',
    iosBundleId: 'com.example.schedulegenerator',
  );

}